version: "3.8"

services:
  frontend:
    build: frontend
    container_name: frontend
    ports:
      - 3000:3000
    stdin_open: true
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api

  api:
    build: api
    container_name: api
    ports:
      - 8080:8080
    volumes:
      - ./api:/app
      - /app/node_modules
    depends_on:
      - mongo

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - ./data:/data/db
    expose:
      - 27017